### ISSUE TITLE
Import Database in RDS (dev)

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#2979]
Blocked by https://github.com/mozmeao/infra/issues/654

**Comment by glogiotatidis** [comment]
We now have a new dev database with enough space. 

@jgmize @metadave since ci.us-west cannot directly connect to this database can you advise on how can we import the sql dump?

**Comment by metadave** [comment]
The easiest way is to start a pod in Frankfurt in the same VPC as the DB. Given the size of the DB backup file, we'll need an attached EBS volume.

**Comment by metadave** [comment]
something like this should work:

```
apiVersion: v1
kind: Pod
metadata:
  name: dbadmin
spec:
  containers:
  - image: debian
    name: dbadmin
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - mountPath: /meao
      name: meao
  volumes:
  - name: meao
    awsElasticBlockStore:
      volumeID: <volume-id>
      fsType: ext4
```
